flowchart TD
    A[Start] --> B[/Enter a month 1-12/]
    B --> C{Is month valid?}
    C -->|No| D[Display Invalid month]
    D --> E[End]
    C -->|Yes| F[/Enter a year/]
    F --> G[Initialize days to 0]
    G --> H[Initialize monthName to empty]
    H --> I{Switch month}
    
    I -->|1| J[Set monthName to January<br>Set days to 31]
    I -->|2| K{Is leap year?}
    I -->|3| L[Set monthName to March<br>Set days to 31]
    I -->|4| M[Set monthName to April<br>Set days to 30]
    I -->|5| N[Set monthName to May<br>Set days to 31]
    I -->|6| O[Set monthName to June<br>Set days to 30]
    I -->|7| P[Set monthName to July<br>Set days to 31]
    I -->|8| Q[Set monthName to August<br>Set days to 31]
    I -->|9| R[Set monthName to September<br>Set days to 30]
    I -->|10| S[Set monthName to October<br>Set days to 31]
    I -->|11| T[Set monthName to November<br>Set days to 30]
    I -->|12| U[Set monthName to December<br>Set days to 31]
    
    K -->|Yes| V[Set days to 29]
    K -->|No| W[Set days to 28]
    
    J --> X[Display result]
    V --> X
    W --> X
    L --> X
    M --> X
    N --> X
    O --> X
    P --> X
    Q --> X
    R --> X
    S --> X
    T --> X
    U --> X
    
    X --> E[End]